let data;
let artData;
let endpoint = "https://api.artic.edu/api/v1/artworks";
let img;
let pieces = [];
let imageLoaded = false;
let loadRandom = true;
let pieceGen = false;
let pieceCount = [2,0];
let xDims;
let yDims;
let prefxDims;
let prefyDims;
let currentlyGrabbed = null;
let grabbedX;
let grabbedY;
let piecesToDraw = [];
let pieceMap;
let maxDim;
let visited = [];
let component = [];
let showingImage = false;
let referenceImage;
let started = false;
let textFadeCounter = 0;
let fade = 2;
let density;
let origMouseX,origMouseY;
let previewImgWidth,previewImgHeight;
// let previewLoaded = false;